### ISSUE TITLE
No transcription received

### ISSUE THREAD

**Issue by bkarakashev** [fabio-garavini/ha-openai-whisper-stt-api#4]
Logger: custom_components.openai_whisper_cloud.const
Source: custom_components/openai_whisper_cloud/stt.py:171
integration: Whisper Cloud ([documentation](https://github.com/fabio-garavini/ha-openai-whisper-stt-api), [issues](https://github.com/fabio-garavini/ha-openai-whisper-stt-api/issues))
First occurred: 8:16:35 pm (2 occurrences)
Last logged: 8:18:21 pm

No transcription received

**Comment by fabio-garavini** [comment]
Can you provide more informations about your configuration? Do you have a vaild api key?

**Comment by bkarakashev** [comment]
Yes, do I need any payment method for this to work?

**Comment by fabio-garavini** [comment]
If you're using GroqClod no, with Openai yes

**Comment by bkarakashev** [comment]
Once I switch to GroqClod everything works great, but it seems OpenAI is paid or something else.

**Comment by fabio-garavini** [comment]
Yes OpenAI api isn't free
