### ISSUE TITLE
Feature Request: Change Base-URL of openai

### ISSUE THREAD

**Issue by Nold360** [fabio-garavini/ha-openai-whisper-stt-api#6]
I'm running a local instance of LocalAI and would like to use it with this plugin. For this to work i need to change the base-url of the openai api. Please make it configurable.

It would also be great (but not needed for my use-case) if you could change the model name as free-text.

**Comment by fabio-garavini** [comment]
Thanks, I'll add it

**Comment by fabio-garavini** [comment]
Updated
take a look at version [1.2.0](https://github.com/fabio-garavini/ha-openai-whisper-stt-api/releases/tag/1.2.0)
